# Generated by Django 2.2.6 on 2019-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191021_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='news',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='news',
            field=models.ManyToManyField(null=True, to='news.News'),
        ),
    ]
