# Generated by Django 2.2.6 on 2019-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191021_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='news',
            field=models.ManyToManyField(to='news.News'),
        ),
    ]
